FROM clarkchan/rpi-tensorflow
RUN pip install translation
RUN mkdir /tmp/imagenet
COPY tmp/imagenet/classify_image_graph_def.pb /tmp/imagenet/
COPY tmp/imagenet/imagenet_2012_challenge_label_map_proto.pbtxt /tmp/imagenet
